//
//  FDNote.m
//  FreshdeskSDK
//
//  Created by AravinthChandran on 30/10/14.
//  Copyright (c) 2014 Freshdesk. All rights reserved.
//

#import "FDNote.h"
#import "FDTicket.h"
#import "MobiHelpDatabase.h"
#import "FDDateUtil.h"
#import "FDAPI.h"
#import "FDMacros.h"

@implementation FDNote

@dynamic body;
@dynamic createdDate;
@dynamic incoming;
@dynamic localNoteID;
@dynamic noteID;
@dynamic pending;
@dynamic source;
@dynamic unread;
@dynamic hasAttachment;
@dynamic attachmentOriginal;
@dynamic attachmentThumbnail;
@dynamic ticket;

+(FDNote *)noteWithInfo:(NSDictionary *)noteInfo inManagedObjectContext:(NSManagedObjectContext *)context{
    FDNote *note                 = nil;
    NSString *noteID             = [noteInfo valueForKeyPath:@"note.id"];
    NSFetchRequest *fetchRequest = [NSFetchRequest fetchRequestWithEntityName:MOBIHELP_DB_NOTE_ENTITY];
    fetchRequest.predicate       = [NSPredicate predicateWithFormat:@"noteID == %@",noteID];
    NSError *error;
    NSArray *matches = [context executeFetchRequest:fetchRequest error:&error];
    if (error || [matches count]>1) {
        FDLog(@"Mobihelp Database error when finding an unique note OR Warning!!! noteID is not unique");
    }else if ([matches count]==1){
        note = [matches firstObject];
    }else{
        note                 = [NSEntityDescription insertNewObjectForEntityForName:MOBIHELP_DB_NOTE_ENTITY inManagedObjectContext:context];
        note.noteID          = [noteInfo valueForKeyPath:@"note.id"];
        note.body            = trimString([noteInfo valueForKeyPath:@"note.body"]);
        NSString *dateString = [noteInfo valueForKeyPath:@"note.created_at"];
        note.createdDate     = [FDDateUtil getRFC3339DateFromString:dateString];
        note.incoming        = [noteInfo valueForKeyPath:@"note.incoming"];
        note.source          = [noteInfo valueForKeyPath:@"note.source"];
        note.unread          = [noteInfo valueForKey:@"unread"];
    }
    return note;
}

+(FDNote *)firstNoteWithEnclosingTicket:(FDTicket *)ticket inManagedObjectContext:(NSManagedObjectContext *)context{
    FDLog(@"Ticket ID %@",ticket.ticketID);
    FDNote *note     = [NSEntityDescription insertNewObjectForEntityForName:MOBIHELP_DB_NOTE_ENTITY inManagedObjectContext:context];
    note.noteID      = @([[NSDate date]timeIntervalSince1970]);
    note.body        = ticket.ticketDescription;
    note.pending     = @NO;
    note.unread      = @NO;
    note.incoming    = @YES;
    note.createdDate = ticket.createdDate;;
    note.ticket      = ticket;
    return note;
}

+(FDNote *)autoGeneratedNoteWithEnclosingTicket:(FDTicket *)ticket inManagedObjectContext:(NSManagedObjectContext *)context{
    FDNote *note     = [NSEntityDescription insertNewObjectForEntityForName:MOBIHELP_DB_NOTE_ENTITY inManagedObjectContext:context];
    note.noteID      = @(NSDate.date.timeIntervalSince1970);
    note.body        = FDLocalizedString(@"Autogenerated Reply");
    note.pending     = @NO;
    note.unread      = @NO;
    note.incoming    = @NO;
    note.createdDate = [ticket.createdDate dateByAddingTimeInterval:1];
    note.ticket      = ticket;
    return note;
}

@end
