//
//  FDNote.h
//  FreshdeskSDK
//
//  Created by AravinthChandran on 30/10/14.
//  Copyright (c) 2014 Freshdesk. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

@class FDTicket;

@interface FDNote : NSManagedObject

@property (nonatomic, retain) NSString * body;
@property (nonatomic, retain) NSDate * createdDate;
@property (nonatomic, retain) NSNumber * incoming;
@property (nonatomic, retain) NSNumber * localNoteID;
@property (nonatomic, retain) NSNumber * noteID;
@property (nonatomic, retain) NSNumber * pending;
@property (nonatomic, retain) NSNumber * source;
@property (nonatomic, retain) NSNumber * unread;
@property (nonatomic, retain) NSNumber * hasAttachment;
@property (nonatomic, retain) NSData * attachmentOriginal;
@property (nonatomic, retain) NSData * attachmentThumbnail;
@property (nonatomic, retain) FDTicket *ticket;

+(FDNote *)noteWithInfo:(NSDictionary *)noteInfo inManagedObjectContext:(NSManagedObjectContext *)context;
+(FDNote *)firstNoteWithEnclosingTicket:(FDTicket *)ticket inManagedObjectContext:(NSManagedObjectContext *)context;
+(FDNote *)autoGeneratedNoteWithEnclosingTicket:(FDTicket *)ticket inManagedObjectContext:(NSManagedObjectContext *)context;


@end
