//
//  FDConstants.h
//  FreshdeskSDK
//
//  Created by Hrishikesh on 07/11/14.
//  Copyright (c) 2014 Freshdesk. All rights reserved.
//

#ifndef FreshdeskSDK_FDConstants_h
#define FreshdeskSDK_FDConstants_h

#define MOBIHELP_SDK_VERSION @"DEVELOPER_VERSION"
#define MOBIHELP_DEFAULT_THEME @"FDLightTheme"

#define MOBIHELP_CONSTANTS_LOG_COUNT_LIMIT   400
#define MOBIHELP_CONSTANTS_BREADCRUMB_LIMIT  50
#define MOBIHELP_CONSTANTS_CUSTOM_DATA_LIMIT 20

#define MOBIHELP_CONSTANTS_NOTE_SOURCE @"10"

//CoppaCompliance Sensitivity
#define MH_SENSITIVITY @"MH_SENSITIVITY"


//FETCH INTERVALS
#ifdef DEBUG
    #define CONFIG_FETCH_INTERVAL 1
    #define UNREAD_COUNT_UPDATE_INTERVAL 1
    #define NEW_ARTICLE_FETCH_INTERVAL 1
    #define TICKET_LIST_FETCH_INTERVAL 4
#else
    #define CONFIG_FETCH_INTERVAL 86400
    #define UNREAD_COUNT_UPDATE_INTERVAL 120
    #define NEW_ARTICLE_FETCH_INTERVAL 300
    #define TICKET_LIST_FETCH_INTERVAL 30
#endif

#define NOTE_LIST_POLLING_INTERVAL 10

//MOBIHELP APP STATE
#define MOBIHELP_STATUS_CODE_INVALID_APP_CREDENTIALS 20
#define MOBIHELP_STATUS_CODE_APP_DELETED             30

//TICKET STATUS CODES
#define MOBIHELP_TICKET_STATUS_OPEN            2
#define MOBIHELP_TICKET_STATUS_PENDING         3
#define MOBIHELP_TICKET_STATUS_RESOLVED        4
#define MOBIHELP_TICKET_STATUS_CLOSED          5
#define MOBIHELP_TICKET_STATUS_AWAITING_REPLY  6
#define MOBIHELP_TICKET_STATUS_BEING_PROCESSED 7

#endif
