# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftSample' do
  use_frameworks!
  pod 'FreshchatSDK', :git => 'https://github.com/freshdesk/freshchat-ios', :branch => 'canary'
end
