//
//  FDThemeConstants.h
//  FreshdeskSDK
//
//  Created by kirthikas on 19/06/15.
//  Copyright (c) 2015 Freshdesk. All rights reserved.
//

#ifndef FreshdeskSDK_FDThemeConstants_h
#define FreshdeskSDK_FDThemeConstants_h

#define FD_THEMES_DIR @"Themes"
#define FD_DEFAULT_THEME_NAME @"HLTheme"
#define FD_FONT_SIZE_LARGE [UIFont preferredFontForTextStyle:UIFontTextStyleHeadline].pointSize
#define FD_FONT_SIZE_MEDIUM [UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline].pointSize
#define FD_FONT_SIZE_NORMAL [UIFont preferredFontForTextStyle:UIFontTextStyleBody].pointSize
#define FD_FONT_SIZE_SMALL [UIFont preferredFontForTextStyle:UIFontTextStyleFootnote].pointSize
#define FD_FONT_SIZE_VERY_SMALL [UIFont preferredFontForTextStyle:UIFontTextStyleCaption2].pointSize
#define FD_COLOR_WHITE @"FFFFFF"
#define FD_COLOR_BLACK @"000000"
#define FD_COLOR_RED @"FF0000"
#define FD_COLOR_GRAY @"D3D3D3"
#define FD_BUTTON_COLOR @"0079FF"
#define FD_NAVIGATION_BAR_BACKGROUND @"F8F8F8"
#define FD_BACKGROUND_COLOR @"FFFFFF"
#define FD_SEARCH_BAR_FONT_COLOR @"D3D7DD"
#define FD_SEARCH_BAR_OUTER_BACKGROUND_COLOR @"F8F8F8"
#define FD_FEEDBACK_FONT_COLOR @"222222"
#define FD_BADGE_BUTTON_BACKGROUND_COLOR @"0066FF"
#define FD_TABLEVIEW_SEPARATOR_COLOR @"F2F2F2"
#define FD_FEEDBACK_VIEW_USER_FIELD_BACKGROUND_COLOR @"F5F5F5"
#define FD_FEEDBACK_VIEW_PLACEHOLDER_COLOR @"B3B3B3"
#define FD_CONVERSATIONS_UI_LAST_UPDATED_TIME_COLOR @"9D9D9D"
#define FD_CONVERSATIONS_UI_HYPERLINK_COLOR @"2701A0"
#define FD_DIALOGUES_YES_BUTTON_FONT_COLOR @"FFFFFF"
#define FD_DIALOGUES_NO_BUTTON_FONT_COLOR @"000000"
#define FD_DIALOGUES_YES_BUTTON_BACKGROUND_COLOR @"007AFF"
#define FD_DIALOGUES_NO_BUTTON_BACKGROUND_COLOR @"F2F2F2"
#define FD_DIALOGUES_NO_BUTTON_BORDER_COLOR @"FFFFFF"
#define FD_DIALOGUES_YES_BUTTON_BORDER_COLOR @"007AFF"
#define FD_DIALOGUES_BACKGROUND_COLOR @"F2F2F2"
#define FD_ARTICLE_LIST_FONT_COLOR @"525252"
#define FD_DIALOGUE_BUTTON_COLOR @"007AFF"
#define FD_CONVERSATIONS_UI_RECEIVED_MESSAGE_FONT_COLOR @"4E4E4E"
#define FD_FAQS_ITEM_SEPARATOR_COLOR @"F2F2F2"
#define FD_CONVERSATION_VIEW_TITLE_TEXT_COLOR @"000000"
#define FD_CONVERSATION_VIEW_BACKGROUND_COLOR @"FFFFFF"
#define FD_ACTION_BUTTON_TEXT_COLOR @"FFFFFF"
#define FD_ACTION_BUTTON_COLOR @"050505"
#define FD_BUSINESS_MESSAGE_TEXT_COLOR @"000000"
#define FD_USER_MESSAGE_TEXT_COLOR @"050505"
#define FD_HYPERLINKCOLOR @"050505"
#define FD_SEND_BUTTON_COLOR @"0079FF"
#define FD_TALK_TO_US_BG_COLOR @"4D90E9"

#endif
